### ISSUE TITLE
Improve responsive IDE layout

### ISSUE THREAD

**Issue by SillyFreak** [PRIArobotics/hedgehog-ide#11]
The IDE's controls scale with the browser window, but some aspects of this are suboptimal:

- the console output and input overlap at low window heights
- the run & save buttons are hidden at low window widths
- file and folder names wrap under their respective icons in the file tree at low window widths

**Comment by kleiinnn** [comment]
All issues listed were fixed with the last commits.
In general, various UI improvements (e.g. movable split view) have been implemented.

Closing this issue for now, feel free to reopen if further problems are discovered.
