### ISSUE TITLE
Integrate sensor pullups into blockly

### ISSUE THREAD

**Issue by kleiinnn** [PRIArobotics/hedgehog-ide#24]
The visual programming environment should allow to set sensor pullups.

**Comment by hmohamad** [comment]
Please provide some python code examples with a short explaination.

**Comment by kleiinnn** [comment]
The pullup can be set via the `hedgehog.set_input_state(port, pullup)` method where `pullup` is a boolean which specifies the whether the sensor pullup should be enabled or not. This will set the input setup globally and across multiple executions. Thus, I suggest to add a new block rather than integrating it into the existing `get_analog` and `get_digital` blocks.

**Comment by hmohamad** [comment]
@kleiinnn please review [9054e25](https://github.com/PRIArobotics/hedgehog-ide/commit/9054e25feae52f094a2a82ece04abdee6233dd0d) and close this issue if it is solved.

**Comment by kleiinnn** [comment]
Looks good 👍
