### ISSUE TITLE
Authentication doesn't work

### ISSUE THREAD

**Issue by Sascha8a** [PRIArobotics/hedgehog-ide#37]
On the newest release (1.2.0) authentication doesn't work at all. The post data from the browser to the server doesn't contain the username and password, just simple empty strings.

**Comment by trestoa** [comment]
The authentication can be enabled/disabled via the server configuration, have you maybe set the `auth.enabled` property to `false`?

**Comment by Sascha8a** [comment]
It's defenetively enabled, otherwise the auth-guard wouldn't show up..

**Comment by trestoa** [comment]
Apparently, the `username` and `password` variables are reset before the HTTP request with the login credentials is being sent. We will soon publish a patch release fixing this issue. 
Thanks for submitting 👍

**Comment by trestoa** [comment]
Fixed with version 1.2.1 (82e9455dead36561312c05e14c54c63ca243cb14).
