### ISSUE TITLE
Can't create new programs

### ISSUE THREAD

**Issue by Sascha8a** [PRIArobotics/hedgehog-ide#38]
On the newest release of the ide it's not possible to create new programs.
![Gif showing the exact error](https://media.giphy.com/media/xT4ApsP6KkLheOPEEE/giphy.gif)

**Comment by SillyFreak** [comment]
Have you tried entering a name?

**Comment by Sascha8a** [comment]
No, because as soon as I click on it it closes again. I can't interact with
it at all.

**Comment by trestoa** [comment]
Unfortunately, I cannot reproduce this behavior on my or any other system we already used this release on. Can you please provide more information on your environment/setup/browser?

**Comment by Sascha8a** [comment]
Raspberry pi model 3, Node v9.0.0, Rasbian OS

**Comment by SillyFreak** [comment]
as this does not happen on our devices, two more questions:
- were you using the [archived](https://github.com/PRIArobotics/hedgehog-ide/releases/tag/v1.2.0) version released by us, or always self-compiled versions?
- does the same happen with Node 7.9.0, which is currently the version we install on our Hedgehogs?
this should help us reproduce the problems. I hope we can resolve this quickly.

**Comment by Kola50011** [comment]
1. We always tried with the self-compiled versions
2. The node version we are using: https://nodejs.org/dist/latest/node-v9.0.0-linux-armv7l.tar.xz

**Comment by trestoa** [comment]
Are you using the the IDE with the production or the debug environment? 
As we unable to reproduce this behavior, could you please create zip file of you build folder and upload it here? This would help us a lot with tracing the error.

**Comment by Kola50011** [comment]
We are using the debug environment

[build.zip](https://github.com/PRIArobotics/hedgehog-ide/files/1439570/build.zip)

**Comment by trestoa** [comment]
Ok, now I see this error as well. Before we work on the actual issue, I would like to find out why your build result is different from ours. The first thing which comes to my mind is that you have installed different versions of the npm build dependencies. Especially a different version of webpack could easily cause a different client code bundle. 
Can you please upload the npm dependency graph (output of `npm list`) so we can check whether there are any differences? I also attached my list [here](https://github.com/PRIArobotics/hedgehog-ide/files/1439629/dependencies.txt) for the reference.

**Comment by Sascha8a** [comment]
Okay.. SO

After removing the node_modules folder and re-compiling everything using NPM instead of yarn we were able to fix the problem. Apparently the materialise-css peer dependency is not installed automatically when using yarn - this could be a cause of the problem.

We were able to fix this issue.
