### ISSUE TITLE
Struggles the children had during the workshop

### ISSUE THREAD

**Issue by nicolemelanie** [PRIArobotics/hedgehog-ide#39]
* the IDE sometimes hangs itself when you press the play/stopp button more than once
* if you want to make a new program the children often struggle with moving the mouse in a way that the selection does not close itself

**Comment by trestoa** [comment]
The run / stop button is now disabled while a command is pending, which will prevent the IDE from handing. Also, the add program button is now click-to-toggle. The menu only closes when the button is pressed a second time which should not happen accidentally.
