### ISSUE TITLE
Directory items array duplex

### ISSUE THREAD

**Issue by tfellner-tgm** [PRIArobotics/hedgehog-ide#5]
Within the `items` array of any folder every item is duplicated.

**Comment by kleiinnn** [comment]
Can you please provide more information about the observed behavior? 
Especially, how can I reproduce it? (Code examples)

As it seems to be a problem with program management, which program storage are you using?

**Comment by tfellner-tgm** [comment]
The `items` Array  within `DummyProgramStorage` in the file [DummyProgramStorage.ts](https://github.com/PRIArobotics/hedgehog-ide/blob/master/src/common/versioncontrol/DummyProgramStorage.ts). The error occurs in [text-id.component.ts](https://github.com/PRIArobotics/hedgehog-ide/blob/master/src/client/app/text-ide/text-ide.component.ts) where the program is initialized from line 51 - 61. Within the `populateFiletree` function on line 85 the `items` array is iterated through and here every item is duplicated and therefore the resulting file tree is wrong.

**Comment by kleiinnn** [comment]
390273880ca90b0f3ab12e5754c20a65301c48b4 should fix this.
