### ISSUE TITLE
Move WorkingTreeObject to another Directory

### ISSUE THREAD

**Issue by tfellner-tgm** [PRIArobotics/hedgehog-ide#6]
There currently is no way of moving a `WorkingTreeObject` to another `WorkingTreeDirectory` meaning you would have to update the `IProgramStorage` and implement it for any other ProgramStorage

**Comment by kleiinnn** [comment]
Actually, there is: https://github.com/PRIArobotics/hedgehog-ide/blob/master/src/common/versioncontrol/ProgramStorage.ts#L185

But it should be possible to specify an absolute path within the `rename` of `WorkingTreeObject`.
