### ISSUE TITLE
Exclude .git Folder from Program WorkingTree

### ISSUE THREAD

**Issue by tfellner-tgm** [PRIArobotics/hedgehog-ide#7]
When (GET) requesting `/api/workingtrees/{program_id}/directories//{directory_id}` with the root directory (`.`) of any Program you get the `.git` which should not be part of a program.

**Comment by kleiinnn** [comment]
I rather think that this is a client side issue by the means that dotfiles and -directories should be hidden by default. There is not reason for me to deny access for certain directories within the REST API.

I am closing this issue for now.
If you have any other arguments, feel free to reopen it.
