### ISSUE TITLE
Simulated Robot does not stop after program termination

### ISSUE THREAD

**Issue by thoebert** [PRIArobotics/hedgehog-ide#76]
A program which only starts the motors but never stops the motors terminates correctly but the simulated robot still continues to run. A simple stop-all after program termination should fix it:)

Besides that - great work! 🥇

**Comment by ensko** [comment]
Thanks Timon :) although this is the wrong Hedgehog IDE, the one with the simulator is over here: https://github.com/PRIArobotics/HedgehogIDE/
